"""
Django settings for villajets project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-z5se%0m5y7wk%wuymlerh&^y0riwaw52g=i@gl5)ry##2mz31%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "admin_interface",
    "colorfield",
    "unfold",  
    "unfold.contrib.filters",
    "unfold.contrib.forms",  
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian", 
    "unfold.contrib.simple_history",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crm",
    "flights"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "villajets.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "villajets.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),        # your DB name
        'USER': os.getenv("DB_USER"),           # your DB user
        'PASSWORD': os.getenv("DB_PASSWORD"),   # your DB password
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

UNFOLD = {
    "SITE_TITLE": "Villaa Jets Admin",
    "SITE_HEADER": "Villaa Jets",
    "SITE_SUBHEADER": _("Luxury Flight Management"),
    "SITE_URL": "/",
    "SITE_SYMBOL": "flight",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,

    "COLORS": {
    "base": {
        "50": "255, 255, 255",
        "100": "245, 245, 245",
        "200": "230, 230, 230",
        "300": "200, 200, 200",
        "400": "160, 160, 160",
        "500": "120, 120, 120",
        "600": "90, 90, 90",
        "700": "60, 60, 60",
        "800": "40, 40, 40",
        "900": "20, 20, 20",
        "950": "10, 10, 10",
    },
    "primary": {
        "50": "239, 246, 255",
        "100": "219, 234, 254",
        "200": "191, 219, 254",
        "300": "147, 197, 253",
        "400": "96, 165, 250",
        "500": "59, 130, 246",
        "600": "37, 99, 235",
        "700": "29, 78, 216",
        "800": "30, 64, 175",
        "900": "30, 58, 138",
        "950": "23, 37, 84",
    },
    "font": {
        "subtle-light": "rgb(90, 90, 90)",      # readable on light bg
        "subtle-dark": "rgb(200, 200, 200)",    # readable on dark bg
        "default-light": "rgb(60, 60, 60)",     # dark gray text on light bg
        "default-dark": "rgb(230, 230, 230)",   # light gray text on dark bg
        "important-light": "rgb(0, 0, 0)",      # pure black for important text
        "important-dark": "rgb(255, 255, 255)", # pure white for important text
    },
}
,

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("CRM"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Leads", "icon": "bolt", "link": reverse_lazy("admin:crm_lead_changelist")},
                    {"title": "Clients", "icon": "person", "link": reverse_lazy("admin:crm_client_changelist")},
                    {"title": "Documents", "icon": "description", "link": reverse_lazy("admin:crm_document_changelist")},
                ],
            },
            {
                "title": _("Flights"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Flight Requests", "icon": "flight_takeoff", "link": reverse_lazy("admin:flights_flightrequest_changelist")},
                    {"title": "Quotes", "icon": "attach_money", "link": reverse_lazy("admin:crm_flightquote_changelist")},
                    {"title": "Flights", "icon": "airplane_ticket", "link": reverse_lazy("admin:flights_flight_changelist")},
                    {"title": "Checklists", "icon": "checklist", "link": reverse_lazy("admin:flights_flightchecklist_changelist")},
                ],
            },
            {
                "title": _("Feedback"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Customer Feedback", "icon": "feedback", "link": reverse_lazy("admin:crm_customerfeedback_changelist")},
                ],
            },
        ],
    },
}