# Generated by Django 5.2.1 on 2025-06-12 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_rename_issued_country_document_document_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country', models.CharField(max_length=3)),
                ('visa_type', models.CharField(blank=True, choices=[('VISA', 'Visa required'), ('EVISA', 'e-Visa'), ('VOA', 'Visa on arrival'), ('NONE', 'No visa needed'), ('OTHER', 'Other / check notes')], editable=False, max_length=5)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
            options={
                'verbose_name': 'Visa check',
                'verbose_name_plural': 'Visa checks',
                'ordering': ('-checked_at',),
            },
        ),
        migrations.CreateModel(
            name='VisaCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(choices=[('VISA', 'Visa required'), ('EVISA', 'e-Visa'), ('VOA', 'Visa on arrival'), ('NONE', 'No visa needed'), ('OTHER', 'Other / check notes')], max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.document')),
                ('visa_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='visa.visacheck')),
            ],
            options={
                'verbose_name': 'Visa check result',
                'verbose_name_plural': 'Visa check results',
                'ordering': ('document__document_country',),
            },
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_country', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('destination_country', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('visa_type', models.CharField(choices=[('VISA', 'Visa required'), ('EVISA', 'e-Visa'), ('VOA', 'Visa on arrival'), ('NONE', 'No visa needed'), ('OTHER', 'Other / check notes')], db_index=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visa requirement',
                'verbose_name_plural': 'Visa requirements',
                'indexes': [models.Index(fields=['document_country', 'destination_country'], name='visa_visare_documen_131e33_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_country', 'destination_country'), name='unique_document_destination_rule')],
            },
        ),
    ]
