# Generated by Django 5.2.1 on 2025-06-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightrequest'),
        ),
    ]
