# Generated by Django 5.2.1 on 2025-06-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_destination_flight_notes_flight_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='origin',
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='destination_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_airport_requests', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='origin_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_airport_requests', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='flights.city'),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='destination_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_city_requests', to='flights.city'),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='origin_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_city_requests', to='flights.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='flights.country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='flights.country'),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='destination_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_country_requests', to='flights.country'),
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country_requests', to='flights.country'),
        ),
    ]
