# Generated by Django 5.2.1 on 2025-06-12 14:50

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airport_city_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_airport',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='destination_city', chained_model_field='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_airport_requests', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='destination_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_city_requests', to='flights.city'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_airport',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='origin_city', chained_model_field='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_airport_requests', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='origin_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_city_requests', to='flights.city'),
        ),
    ]
