# Generated by Django 5.2.1 on 2025-06-13 09:18

import django.db.models.deletion
import flights.models
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_update_airport_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='destination_country', chained_model_field='country_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_city_requests', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_country',
            field=models.CharField(blank=True, choices=flights.models.get_country_choices, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='origin_country', chained_model_field='country_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_city_requests', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_country',
            field=models.CharField(blank=True, choices=flights.models.get_country_choices, max_length=200, null=True),
        ),
    ]
