# Generated by Django 5.2.1 on 2025-06-13 09:23

import django.db.models.deletion
import flights.models
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_flightrequest_destination_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightrequest',
            options={'verbose_name': 'Flight Request', 'verbose_name_plural': 'Flight Requests'},
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_airport',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='destination_city', chained_model_field='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_airport_requests', to='flights.airport', verbose_name='Destination Airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='destination_country', chained_model_field='country_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_city_requests', to='flights.airport', verbose_name='Destination City'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_country',
            field=models.CharField(blank=True, choices=flights.models.get_country_choices, max_length=200, null=True, verbose_name='Destination Country'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_airport',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='origin_city', chained_model_field='city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_airport_requests', to='flights.airport', verbose_name='Origin Airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='origin_country', chained_model_field='country_name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_city_requests', to='flights.airport', verbose_name='Origin City'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_country',
            field=models.CharField(blank=True, choices=flights.models.get_country_choices, max_length=200, null=True, verbose_name='Origin Country'),
        ),
    ]
