# Generated by Django 5.2.1 on 2025-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_flightrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Destination Country'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Origin Country'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['country_name'], name='flights_air_country_8d07ef_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city'], name='flights_air_city_5a6128_idx'),
        ),
    ]
