# Generated by Django 5.2.1 on 2025-06-13 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_rename_issued_country_document_document_country'),
        ('flights', '0008_alter_flightrequest_destination_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportsDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='airport',
            name='flights_air_country_8d07ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='airport',
            name='flights_air_city_5a6128_idx',
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='iata_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_airport_requests', to='flights.airport', verbose_name='Destination Airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_city_requests', to='flights.airport', verbose_name='Destination City'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='destination_country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Destination Country'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_airport_requests', to='flights.airport', verbose_name='Origin Airport'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_city_requests', to='flights.airport', verbose_name='Origin City'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='origin_country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Origin Country'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['country_name', 'city'], name='flights_air_country_c28a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city', 'name'], name='flights_air_city_aef6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='flightrequest',
            index=models.Index(fields=['departure_date', 'return_date'], name='flights_fli_departu_c4bd67_idx'),
        ),
    ]
