# Generated by Django 5.2.1 on 2025-06-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_airportsdatacache_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrequest',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='origin_city',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='origin_country',
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField()),
                ('passengers', models.PositiveIntegerField()),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flights.airport')),
                ('flight_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='flights.flightrequest')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flights.airport')),
            ],
            options={
                'ordering': ['departure_date'],
            },
        ),
    ]
