# Generated by Django 5.2.1 on 2025-06-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_remove_flightrequest_destination_city_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flightrequest',
            name='flights_fli_departu_c4bd67_idx',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='origin_airport',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='return_date',
        ),
    ]
