# Generated by Django 5.2.1 on 2025-05-15 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerfeedback",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flights.flight"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="crm.client",
            ),
        ),
        migrations.AddField(
            model_name="flightquote",
            name="client",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="crm.client"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.client"
            ),
        ),
    ]
