# Generated by Django 5.2.1 on 2025-06-04 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Mail Credentials',
                'verbose_name_plural': 'Mail Credentials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.mail',),
        ),
        migrations.AddField(
            model_name='mail',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='crm.client'),
        ),
    ]
