# Generated by Django 5.2.1 on 2025-06-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_client_created_at_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='username',
            new_name='sender',
        ),
    ]
