# Generated by Django 5.2.1 on 2025-06-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_username_mail_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='issued_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
