# Generated by Django 5.2.1 on 2025-06-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_document_issued_country_alter_document_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='issued_country',
            new_name='document_country',
        ),
    ]
