# Generated by Django 5.2.1 on 2025-05-15 08:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("quoted", "Quoted"),
                            ("accepted", "Accepted"),
                            ("prepared", "Prepared"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("scheduled_departure", models.DateTimeField()),
                ("scheduled_return", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlightChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airports_ready", models.BooleanField(default=False)),
                ("itinerary_ready", models.BooleanField(default=False)),
                ("crew_ready", models.BooleanField(default=False)),
                ("customs_ready", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flight",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="flights.flight"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passengers", models.PositiveIntegerField()),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("origin", models.CharField(max_length=255)),
                (
                    "destinations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        help_text="List of one or more destination airports/locations",
                        size=None,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.client"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flight",
            name="flight_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="flights.flightrequest"
            ),
        ),
        migrations.CreateModel(
            name="PlaneRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100)),
                ("seat_count", models.PositiveIntegerField()),
                ("other_requirements", models.TextField(blank=True)),
                (
                    "flight_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flights.flightrequest",
                    ),
                ),
            ],
        ),
    ]
